---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: sample ec2 key
      ec2_key:
        name: test_key
        region: us-east-2
      register: keyout
  - debug: null
      var: keyout
